version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: 551155
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"

  django-ecommerce:
    build:
      context: .   # Path to the Dockerfile for Django app 1
    container_name: ecommerce
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

volumes:
  mysql_data:

# version: '3'

# services:






#   django:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"

#     networks:
#       - backend



# networks:
#   backend:
#     driver: bridge
